### ISSUE TITLE
Right prompt is drawn at the bottom of the screen

### ISSUE THREAD

**Issue by heysokam** [jnoortheen/xontrib-powerline3#11]
The right prompt is being drawn on the bottom of the screen
It is also being redrawn at the top after one command is run
![image](https://user-images.githubusercontent.com/7308253/197469400-3c3b9cf5-4894-433b-80ed-6b80fa908d4a.png)
I just installed the xontrib, so maybe I'm doing something wrong in my config. I used the defaults shown on the readme
Is there a way this can be fixed?

**Comment by jnoortheen** [comment]
that is an [issue](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1241) from ptk. You can install it with my [fix](https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1591)

**Comment by heysokam** [comment]
I see, ty
Where can I find this file in my computer, so that I can apply the fix?

**Comment by jnoortheen** [comment]
if you've installed it with venv, you can look inside `site-packages/prompt_toolkit/shortcuts/prompt.py` .
