### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by eode** [jnoortheen/xontrib-powerline3#4]
Powerline2 has a status bar, but currently that isn't doable with powerline3.

**Comment by jnoortheen** [comment]
what do you mean by status bar?

**Comment by eode** [comment]
A bar along the bottom of the screen as is done with Powerline 2 or Powerline's `$PL_TOOLBAR` variable, as visible [here](https://github.com/santagada/xontrib-powerline/raw/master/screenshot.png).

Incidentally, I like direction you're going with this.  It feels more directly integrated into Xonsh.

**Comment by jnoortheen** [comment]
you could just use https://xon.sh/envvars.html#bottom-toolbar

The idea here is to use this library as a theme and not bring its own set of configurations as much as possible.

**Comment by eode** [comment]
Thanks!  I was unaware of the existence of `$BOTTOM_TOOLBAR`, it has been added since I started using Xonsh.
