### ISSUE TITLE
Value for `$RIGHT_PROMPT` placement error

### ISSUE THREAD

**Issue by eode** [jnoortheen/xontrib-powerline3#6]
I have the setting `$RIGHT_PROMPT='meow'` (to keep it as simple as possible).

After a clear, the `meow` shows up on the bottom right.
After hitting enter, the `meow` shows up at the end of the line *above* the current prompt (the line I just left).

**Comment by jnoortheen** [comment]
It is a problem with prompt-toolkit rendering. It was fine until few version updates.
