### ISSUE TITLE
ret_code not parsed

### ISSUE THREAD

**Issue by sbliven** [jnoortheen/xontrib-powerline3#7]
I am trying to use `{ret_code}` in my prompt but it get's printed literally:

```
{ret_code}>~>$>
```

In my xonshrc I have
```
$POWERLINE_MODE = "powerline"
$PROMPT = "".join(
    [
        "{ret_code}",
        "{full_env_name: 🐍{}}",
        "{cwd:{}}",
        "{gitstatus:{}}",
        "{prompt_end}",
    ]
)
```

I copied this from the README, but I didn't really understand the formatting syntax.

**Comment by jnoortheen** [comment]
that prompt-field comes from `prompt_ret_code` xontrib. 

You need to load it by either 

```
xontrib load prompt_ret_code 

or 

import xontrib.prompt_ret_code
```

**Comment by jnoortheen** [comment]
thanks for reminding. Now the README is updated.
